<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dsmUML" nsURI="dsmUML" nsPrefix="dsmUML">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="EModelado">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Diagrama" eSuperTypes="#//EModelado">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="nombreClaseUnico"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="nombreClaseUnico" value="&#xA;&#x9;&#x9;&#x9;self.clases->isUnique(nombre)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clases" upperBound="-1"
        eType="ecore:EClass #//Clase" containment="true"
        eOpposite="#//Clase/diagrama"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="asociaciones" upperBound="-1"
        eType="ecore:EClass #//Asociacion" containment="true"
        eOpposite="#//Asociacion/diagrama"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Clase" eSuperTypes="#//EModelado">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="nombreAtributoeUnico nombreRolUnico herenciaSimple"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="nombreAtributoeUnico" value="&#xA;&#x9;&#x9;&#x9;self.atributos->isUnique(nombre)"/>
      <details key="nombreRolUnico" value="&#xA;&#x9;&#x9;&#x9;self.asociacion1->isUnique(rol1) and self.asociacion2->isUnique(rol2)"/>
      <details key="herenciaSimple" value="&#xA;&#x9;        self.sub->collect(c|c.sub)->excludes(self)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagrama" lowerBound="1"
        eType="ecore:EClass #//Diagrama" eOpposite="#//Diagrama/clases"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atributos" upperBound="-1"
        eType="ecore:EClass #//Atributo" containment="true"
        eOpposite="#//Atributo/clase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="asociacion1" upperBound="-1"
        eType="ecore:EClass #//Asociacion" eOpposite="#//Asociacion/clase1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="asociacion2" upperBound="-1"
        eType="ecore:EClass #//Asociacion" eOpposite="#//Asociacion/clase2"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="csuper" eType="ecore:EClass #//Clase"
        eOpposite="#//Clase/sub"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sub" upperBound="-1" eType="ecore:EClass #//Clase"
        eOpposite="#//Clase/csuper"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Atributo" eSuperTypes="#//EModelado">
    <eStructuralFeatures xsi:type="ecore:EReference" name="clase" eType="ecore:EClass #//Clase"
        eOpposite="#//Clase/atributos"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo" eType="ecore:EEnum #//Tipo"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rango" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Asociacion" eSuperTypes="#//EModelado">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="cardianlidades"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="cardianlidades" value="&#xA;&#x9;&#x9;&#x9;(min1&lt; max1 or max1=-1)and (min2&lt;max2 or max2=-1)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clase1" lowerBound="1"
        eType="ecore:EClass #//Clase" eOpposite="#//Clase/asociacion1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clase2" lowerBound="1"
        eType="ecore:EClass #//Clase" eOpposite="#//Clase/asociacion2"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rol1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rol2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagrama" lowerBound="1"
        eType="ecore:EClass #//Diagrama" eOpposite="#//Diagrama/asociaciones"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="claseasociacion" eType="ecore:EClass #//ClaseAsociacion"
        eOpposite="#//ClaseAsociacion/sobre"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Agregacion" eSuperTypes="#//Asociacion">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="cardinalidaAgregacion"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="cardinalidaAgregacion" value="&#xA;&#x9;&#x9;&#x9;if (enclase1) then( min1=1 and max1=1)else (min2=1 and max2=1)endif"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enclase1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClaseAsociacion" eSuperTypes="#//Clase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sobre" lowerBound="1" eType="ecore:EClass #//Asociacion"
        eOpposite="#//Asociacion/claseasociacion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Tipo">
    <eLiterals name="entero"/>
    <eLiterals name="real" value="1"/>
    <eLiterals name="cadena" value="2"/>
  </eClassifiers>
</ecore:EPackage>
